### ISSUE TITLE
Make required percentage of ownership configurable.

### ISSUE THREAD

**Issue by phallstrom** [designfrontier/pythia#5]
https://github.com/designfrontier/pythia/blob/9d5b57b146490d292f24950266926c1d920ac9ba/modules/check-ownership.js#L8

I could see some projects wanting to tweak that number.  Long term it would be slick to make it configurable per pathname regex (ie. 20% for code, 40% for tests, etc)

**Comment by designfrontier** [comment]
Seems like a reasonable thing to do...

I'll see what I can work up, or you're more then welcome to write up a PR that does those. The long term ideas shouldn't be super hard to do either
